import Head from "next/head";

import useWeather from "@/hooks/useWeather";
import styles from "@/styles/Home.module.css";
import Sidebar from "@/components/Sidebar";
import Content from "@/components/Content";
import Loading from "@/components/Loading";

export default function Home() {
  const { loading } = useWeather();

  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Sidebar />
        <Content />
        {loading && <Loading />}
      </main>
    </>
  );
}
